return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "bash-language-server",
        "chrome-debug-adapter",
        -- "clangd",
        -- "cmakelang",
        -- "cmakelint",
        "codelldb",
        -- "css-lsp",
        "debugpy",
        -- "delve",
        "eslint-lsp",
        -- "hadolint",
        -- "jdtls",
        "js-debug-adapter",
        "json-lsp",
        "lua-language-server",
        -- "markdown-toc",
        -- "markdownlint",
        -- "markdownlint-cli2",
        -- "marksman",
        -- "neocmakelsp",
        "prettier",
        "prettierd",
        "ruff",
        "ruff-lsp",
        -- "selene",
        "shellcheck",
        "shfmt",
        -- "sql-formatter",
        -- "sqlfluff",
        "stylua",
        "tailwindcss-language-server",
        -- "tflint",
        "vtsls",
        "yaml-language-server",
      },
    },
  },
}
